--import core lua files to init
require("main.plugins-setup")
require("main.core.options")
require("main.core.keymaps")
require("main.core.colorscheme")
require("main.plugins.comment")
require("main.plugins.nvim-tree")
require("main.plugins.lualine")
require("main.plugins.nvim-cmp")
-- adding lsp support
require("main.plugins.lsp.lsp-config")
require("main.plugins.autopairs")
require("main.plugins.gitsigns")
require("main.plugins.treesitter")
require("main.plugins.toggleterm")
